name = "cuit"
main = "src/index.js"
#main = "src/index.ts"
compatibility_date = "2024-01-10"

[observability]
enabled = true
head_sampling_rate = 1

[ai]
binding = "AI"

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true

[[d1_databases]]
binding = "DATABASE"
database_name = "dni"
database_id = "ceb34e17-751e-42a6-8230-9fdb8c828167"

[[unsafe.bindings]]
name = "VECTOR_INDEX"
type = "vectorize"
index_name = "cuitgpt"

[[workflows]]
name = "rag"
binding = "RAG_WORKFLOW"
class_name = "RAGWorkflow"
